<a href="https://colab.research.google.com/github/janaecameron/Data_Science_Work/blob/main/Janae_Cameron_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [2]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


**commands Python to list all numbers between 0 and 100**

In [3]:
for i in range(5,8):
    print(i)

5
6
7


**commands Python to list numbers between 5 and 8**

In [4]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


**tells Python to place the phrase "Test Number:" infront of each of the numbers that are less than 3 (0, 1, and 2)**

### Functions

In [5]:
def square(x):
    return x**2

**this code is letting us know that whenever we insert a command such as "square(6)" that we will be raising 6 to the power of 2, hence the use of the word "square"**

In [6]:
square(5)

25

**when putting the word "square" followed by a set of parentheses surrounding a number, that is a command for Python to set the number inside the parenthesis to the power of 2, as defined by the code above**

In [7]:
square(square(2))

16

**this specific code tells Python to complete the operation in the parentheses, which is to set 2 to the second power/be squared; once getting the answer to that first operation, which is 4, then that answer needs to be set to the second power/ be squared and the result will be 16**

In [8]:
square(square(square(2)))


256

**just as we did before, we are going to cpmplete the operation within each set of parentheses, starting with the "(square(2))"; knowing that the answer to this operation is 4, we will "square" this answer and get 16; then, once we finally square 16, we will get our final answer of 256**

In [9]:
square(123456)

15241383936

In [10]:
square(square(5))

625

In [11]:
def add_two(x):
    return x+2

**lets Python know that in every command that we give after this which uses this rule, no matter what x is, 2 needs to be added onto that number**

In [12]:
add_two(5)

7

**this command tells Python to add 2 onto the number that is within the parentheses, which in this case is 5**

In [13]:
square(add_two(5))

49

**following the rules of PEMDAS, we will have Python complete what the operation that is within the parentheses first; once we get the total of what is inside the parenthesis, in this case 7, we will raise 7 to the second power, thus giving us an answer of 49**

### Logical Branching

In [14]:
choice = "apple"

In [15]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


**much like the coin flip, this is an at random command, so in order to show whether the choice provided in the code above is the result, Python will either show "You choose apples" or "You did not choose apples"**

In [16]:
choice = "orange"

In [17]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [18]:
choice = "apple"

In [19]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [21]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [22]:
choice

'apple'

In [23]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


**just like the command where "choice = 'oranges'", Python will either show "You choose apples", "You choose oranges", or "You did not choose apples or oranges"**

#### Coins

In [31]:
import numpy as np

In [32]:
np.random.random()

0.9509787338235391

**when inserting the command "np.random.random()" Python will know that when we attempt to run this code, it will give us a number that is in between 0 and 1**

In [33]:
np.random.random() > 0.5

True

**before running this command, it is crucial to run the previous code first because the result of this command is dependent upon the numerical value randomly picked out after running the previous code**

In [34]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

**this command is letting Python know that for every time it completes a "coin flip" and the numerical value is greater than 0.5, then an image of the heads side of a coin (a quarter) will be shown, however, if the numerical value is less than 0.5 Python will show an image of the tails side of a coin**

In [35]:
flip_coin()

Heads


### Graphics Output

In [36]:
from IPython.core.display import display, HTML

**tells Python to import the image or text from the HTML**

In [37]:
display(HTML('<h1>Hello, world!</h1>'))

**tells Python to display the image or text from the HTML, which in this case is "Hello, world!"**

In [38]:
def coin():
  return np.random.randint(2)

In [39]:
coin()

1

In [40]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [41]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

**providing the urls for an image of a quarter showing the heads side and an image of a quarter showing the tails side**

In [42]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

**letting Python know that whenever we attempt to run a command that says "show_img(heads)" or "show_img(tails)" that the image of that particular side of the coin will be displayed after the command is complete**

In [43]:
show_img(heads)

In [44]:
show_img(tails)

In [45]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

**this is letting Python know that everytime the command "flip_coin()" is run to randomly "flip" the coin and report whether it "landed" on heads or tails by showing the image of that particular side**

In [46]:
flip_coin()

In [ ]:
for i in range(5):
    flip_coin()

**this lets Python know to flip the coin 5 times and show the result after each flip**

In [47]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [48]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [49]:
a = np.arange(52)

**this code tells Python that whenever it sees the term "a" this means to involve the entire deck of cards in the command given, which consists of 52 total cards and is signified by the number in the set of parentheses**

In [50]:
shuffle(a)

array([ 1, 51, 50,  6, 33,  4, 20,  7, 22,  8, 23, 30,  5, 17, 14, 31,  9,
       37, 44, 47, 49, 21, 11, 10, 35, 13, 27, 28,  2, 45, 15, 24, 41, 25,
       38, 34, 39, 46, 43,  3, 32, 26, 40, 19, 12, 42, 29, 18, 36, 16, 48,
        0])

**this code tells Python to shuffle the entire deck of cards**

In [51]:
np.random.permutation(52)

array([10, 27,  4, 31, 30, 19, 14, 33,  7, 42, 15, 34,  3, 16, 36,  9, 28,
       26, 38,  6, 17, 21, 25,  1, 29, 44, 40, 47, 39, 43,  0, 35, 20, 49,
       50,  8, 18, 41,  5,  2, 23, 12, 46, 13, 48, 22, 51, 24, 11, 37, 45,
       32])

**this signifies to Python that it must assemble numbers 1 to 52 into whatever random order that occurs**

### Speed Test

In [52]:
%%timeit
shuffle(a)

172 µs ± 4.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [53]:
%%timeit
np.random.permutation(52)

3.51 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [54]:
import numpy as np

In [55]:
np.random.permutation(52)

array([45, 49, 40, 30, 43, 34, 50, 12, 11, 24, 32,  2, 37, 29, 16,  9, 42,
        0, 39, 18, 25, 27, 41, 38, 46, 48, 15,  3, 44, 31, 20, 36, 17,  6,
        7,  5, 10, 14,  8, 22, 13, 35, 28, 51, 21, 33, 47,  1,  4, 23, 26,
       19])

In [56]:
cards = np.random.permutation(52)

**this signifies to Python that it must assemble the shuffled cards into whatever random order that occurs**

In [57]:
cards

array([ 5, 15, 23, 14,  4, 25,  3, 36, 50,  1, 41, 19, 46, 44, 33, 10, 17,
       27, 29, 31, 39, 21, 45, 24,  6, 18, 32, 20, 28, 16, 35, 51, 48,  8,
       13, 37, 11, 34, 40,  9, 43, 49,  7, 26, 22, 12, 38,  2, 42, 30,  0,
       47])

In [58]:
cards[0]

5

In [59]:
cards[1]

15

In [60]:
cards[2]

23

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

**this provides a visual display of a deck of cards when they are arranged into rows order of increasing value and suit type**

In [61]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [62]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [63]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [64]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

**this code separates the cards into 2 separate categories, which are the symbols called suits present on every card respectively and the potential values that any card can have within the deck**

In [65]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

**tells Python that whenever such a code as this one is run that it provides the name of the suit of this particular card**

In [66]:
card_name(0)

'Ace of Clubs'

In [67]:
card_name(51)

'King of Diamonds'

In [68]:
cards = np.random.permutation(52)

In [69]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [70]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Seven of Clubs', 'Ace of Hearts', 'Nine of Diamonds')

**provides the suit type of each of the cards that is at the top of the deck, the second, and at the bottom/the last card within the deck**

In [71]:
for i in range(5):
    print(card_name(cards[i]))

Seven of Clubs
Ace of Hearts
Queen of Clubs
Queen of Hearts
Queen of Spades


**tells Python to provide the name and the number of 5 cards within the deck at random**

In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


**tells Python to provide the name and the number of 15 cards within the deck at random**

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [72]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [73]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [74]:
i = np.random.randint(4)
j = np.random.randint(13)

In [75]:
i,j

(2, 10)

In [76]:
suit[i]

's'

In [77]:
card[j]

'j'

In [78]:
from IPython.core.display import display, HTML

In [79]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

**letting Python know that whenever we attempt to run a command that says "show_img(img)" that an image of the card, which will consist of its number and suit type**

In [80]:
img = card_url_head + suit[i] + card[j] + card_url_tail

**provides the details of what img means**

In [81]:
show_img(img)

In [82]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [83]:
card_image(3)

'k4'

In [84]:
img = card_url_head + card_image(3) + card_url_tail

In [85]:
show_img(img)

In [86]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

**shows the images of all 52 cards in the deck**